default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: code_challenge_api_development

test:
  <<: *default
  database: code_challenge_api_test

production:
  <<: *default
  database: code_challenge_api_production
  username: <%= ENV['CODE_CHALLENGE_API_DATABASE_USERNAME'] %>
  password: <%= ENV['CODE_CHALLENGE_API_DATABASE_PASSWORD'] %>
